version: '3.8'

services:
  hotelchatbot:
    build: .
    ports:
      - "5000:80"  # Exposes the app on port 5000
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection=Server=db;Port=3306;Database=HotelDb;User=root;Password=Root@1234;  # Adjust your connection string here

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Root@1234
      MYSQL_DATABASE: HotelDb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
